morpheu/src/main/java/com/lmsystem/controller/cadastros/PessoaFisicaBean.java
package com.lmsystem.controller.cadastros;

import java.io.IOException;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Bairro;
import com.lmsystem.modelo.Contato;
import com.lmsystem.modelo.Endereco;
import com.lmsystem.modelo.Etnia;
import com.lmsystem.modelo.Municipio;
import com.lmsystem.modelo.Nacionalidade;
import com.lmsystem.modelo.PessoaFisica;
import com.lmsystem.modelo.RacaCor;
import com.lmsystem.modelo.Sexo;
import com.lmsystem.modelo.TipoLogradouro;
import com.lmsystem.repository.BairroRepository;
import com.lmsystem.repository.MunicipioRepository;
import com.lmsystem.services.cadastros.PessoaFisicaRN;
import com.lmsystem.util.BuscaCEP;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class PessoaFisicaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private PessoaFisica pessoaFisica;

	private String nomePessoa;

	private List<PessoaFisica> pessoasFisica;

	@Inject
	protected PessoaFisicaRN pessoaRN;

	@Inject
	protected BairroRepository bairroRepository;

	@Inject
	protected MunicipioRepository municipioRepository;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomePessoa("");
		pesquisar();
	}

	public void novo() {
		this.pessoaFisica = new PessoaFisica();
		this.getPessoaFisica().setContato(new Contato());
		this.getPessoaFisica().setEndereco(new Endereco());
	}

	public void salvar() {
		try {
			pessoaRN.salvar(getPessoaFisica());
			pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.pessoaFisica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			pessoaRN.remover(this.getPessoaFisica());
			this.pesquisar();
			facesUtils.exibeSucesso("registro removido com sucesso!", null);
			this.pessoaFisica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
		}
	}

	public String limpar() {
		return "pessoafisica?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		opcoes.put("resizable", false);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/pessoafisica", opcoes, null);
	}

	public void pesquisar() {
		this.getPessoasFisicas();
	}

	public void buscarCEP() {
		BuscaCEP cep = new BuscaCEP();
		try {
			if (!this.getPessoaFisica().getEndereco().getCep().trim().equals("")
					|| this.getPessoaFisica().getEndereco().getCep() != null) {
				String tmp = cep.getCidade(this.getPessoaFisica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaFisica().getEndereco()
							.setMunicipio(municipioRepository.buscarPorDescricao("municipio", tmp).get(0));
					tmp = null;
				}
				tmp = cep.getEndereco(this.getPessoaFisica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaFisica().getEndereco().setEndereco(tmp);
					tmp = null;
				}
				tmp = cep.getBairro(this.getPessoaFisica().getEndereco().getCep());
				if (tmp != null) {
					System.out.println(tmp);
					this.getPessoaFisica().getEndereco()
							.setBairro(bairroRepository.buscarPorDescricao("bairro", tmp).get(0));
					tmp = null;
				}
			}
		} catch (IOException e) {
			System.out.println("Endereço não encontrado!");
			e.printStackTrace();
		}
	}

	private List<PessoaFisica> getPessoasFisicas() {
		pessoasFisica = pessoaRN.listarTodos(getNomePessoa());
		return pessoasFisica;
	}

	public PessoaFisica getPessoaFisica() {
		return pessoaFisica;
	}

	public void setPessoaFisica(PessoaFisica pessoaFisica) {
		this.pessoaFisica = pessoaFisica;
	}

	public String getNomePessoa() {
		return nomePessoa;
	}

	public void setNomePessoa(String nomePessoa) {
		this.nomePessoa = nomePessoa;
	}

	public List<Sexo> listarSexos(String query) {
		return pessoaRN.listarSexos(query);
	}

	public List<RacaCor> listarRacasCor(String query) {
		return pessoaRN.listarRacasCor(query);
	}

	public List<Etnia> listarEtnias(String query) {
		return pessoaRN.listarEtnias(query);
	}

	public List<Municipio> listarMunicipios(String query) {
		return pessoaRN.listarMunicipios(query);
	}

	public List<Nacionalidade> listarNacionalidades(String query) {
		return pessoaRN.ListarNacionalidades(query);
	}

	public List<TipoLogradouro> listarTiposLogradouro(String query) {
		return pessoaRN.listarTipoLogradouros(query);
	}

	public List<Bairro> listarBairros(String query) {
		return pessoaRN.listarBairros(query);
	}

	public List<PessoaFisica> getPessoasFisica() {
		this.pessoasFisica = pessoaRN.listarTodos(getNomePessoa());
		return pessoasFisica;
	}
}

morpheu/src/main/java/com/lmsystem/controller/cadastros/PessoaJuridicaBean.java
package com.lmsystem.controller.cadastros;

import java.io.IOException;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Bairro;
import com.lmsystem.modelo.Contato;
import com.lmsystem.modelo.Endereco;
import com.lmsystem.modelo.Municipio;
import com.lmsystem.modelo.PessoaJuridica;
import com.lmsystem.modelo.TipoLogradouro;
import com.lmsystem.repository.BairroRepository;
import com.lmsystem.repository.MunicipioRepository;
import com.lmsystem.services.cadastros.PessoaJuridicaRN;
import com.lmsystem.util.BuscaCEP;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class PessoaJuridicaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private PessoaJuridica pessoaJuridica;

	private String nomefantasia;

	private List<PessoaJuridica> pessoasJuridica;

	@Inject
	protected PessoaJuridicaRN pessoaRN;

	@Inject
	protected BairroRepository bairroRepository;

	@Inject
	protected MunicipioRepository municipioRepository;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomefantasia("");
		pesquisar();
	}

	public void novo() {
		this.pessoaJuridica = new PessoaJuridica();
		this.getPessoaJuridica().setContato(new Contato());
		this.getPessoaJuridica().setEndereco(new Endereco());
	}

	public void salvar() {
		try {
			pessoaRN.salvar(getPessoaJuridica());
			pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.pessoaJuridica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			pessoaRN.remover(this.getPessoaJuridica());
			this.pesquisar();
			facesUtils.exibeSucesso("registro removido com sucesso!", null);
			this.pessoaJuridica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
		}
	}

	public String limpar() {
		return "pessoajuridica?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		opcoes.put("resizable", false);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/pessoajuridica", opcoes, null);
	}

	public void pesquisar() {
		this.getPessoasFisicas();
	}

	public void buscarCEP() {
		BuscaCEP cep = new BuscaCEP();
		try {
			if (!this.getPessoaJuridica().getEndereco().getCep().trim().equals("")
					|| this.getPessoaJuridica().getEndereco().getCep() != null) {
				String tmp = cep.getCidade(this.getPessoaJuridica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaJuridica().getEndereco()
							.setMunicipio(municipioRepository.buscarPorDescricao("municipio", tmp).get(0));
					tmp = null;
				}
				tmp = cep.getEndereco(this.getPessoaJuridica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaJuridica().getEndereco().setEndereco(tmp);
					tmp = null;
				}
				tmp = cep.getBairro(this.getPessoaJuridica().getEndereco().getCep());
				if (tmp != null) {
					System.out.println(tmp);
					this.getPessoaJuridica().getEndereco()
							.setBairro(bairroRepository.buscarPorDescricao("bairro", tmp).get(0));
					tmp = null;
				}
			}
		} catch (IOException e) {
			System.out.println("Endereço não encontrado!");
			e.printStackTrace();
		}
	}

	private List<PessoaJuridica> getPessoasFisicas() {
		pessoasJuridica = pessoaRN.listarTodos(getNomefantasia());
		return pessoasJuridica;
	}

	public PessoaJuridica getPessoaJuridica() {
		return pessoaJuridica;
	}

	public void setPessoaJuridica(PessoaJuridica pessoaJuridica) {
		this.pessoaJuridica = pessoaJuridica;
	}

	public String getNomefantasia() {
		return nomefantasia;
	}

	public void setNomefantasia(String nomefantasia) {
		this.nomefantasia = nomefantasia;
	}

	public List<Municipio> listarMunicipios(String query) {
		return pessoaRN.listarMunicipios(query);
	}

	public List<TipoLogradouro> listarTiposLogradouro(String query) {
		return pessoaRN.listarTipoLogradouros(query);
	}

	public List<Bairro> listarBairros(String query) {
		return pessoaRN.listarBairros(query);
	}

	public List<PessoaJuridica> getPessoasJuridica() {
		this.pessoasJuridica = pessoaRN.listarTodos(getNomefantasia());
		return pessoasJuridica;
	}
}

morpheu/src/main/java/com/lmsystem/controller/cadastros/SetorBean.java
package com.lmsystem.controller.cadastros;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Setor;
import com.lmsystem.services.cadastros.SetorRN;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class SetorBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Setor setor;

	private List<Setor> setores;

	private String nomesetor;

	@Inject
	protected SetorRN setorRN;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomesetor("");
		pesquisar();
	}

	public void novo() {
		this.setor = new Setor();
	}

	public void salvar() {
		try {
			setorRN.salvar(this.setor);
			this.setor = new Setor();
			this.pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.setor = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			setorRN.remover(this.setor);
			this.pesquisar();
			facesUtils.exibeSucesso("Registro removido com sucesso!", null);
			this.setor = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public String limpar() {
		return "setor?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/setor", opcoes, null);
	}

	public void pesquisar() {
		this.getSetores();
	}

	public List<Setor> listarSetores(String query) {
		return setorRN.listarTodos(query);
	}

	public Setor getSetor() {
		return setor;
	}

	public void setSetor(Setor setor) {
		this.setor = setor;
	}

	public List<Setor> getSetores() {
		this.setores = setorRN.listarTodos(getNomesetor());
		return setores;
	}

	public String getNomesetor() {
		return nomesetor;
	}

	public void setNomesetor(String nomesetor) {
		this.nomesetor = nomesetor;
	}

}

morpheu/src/main/java/com/lmsystem/controller/cadastros/UsuarioBean.java
package com.lmsystem.controller.cadastros;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Permissoes;
import com.lmsystem.modelo.Usuario;
import com.lmsystem.services.cadastros.UsuarioRN;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class UsuarioBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Usuario usuario;

	private String nomeusuario;

	private List<Usuario> usuarios;

	@Inject
	protected UsuarioRN usuarioRN;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomeusuario("");
		pesquisar();
	}

	public void novo() {
		this.usuario = new Usuario();
	}

	public void salvar() {
		try {
			usuarioRN.salvar(this.usuario);
			this.usuario = new Usuario();
			this.pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.usuario = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			usuarioRN.remover(this.usuario);
			this.pesquisar();
			facesUtils.exibeSucesso("Registro removido com sucesso!", null);
			this.usuario = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public String limpar() {
		return "usuario?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/usuario", opcoes, null);
	}
	
	public Permissoes[] getPermissoes() {
		return Permissoes.values();
	}

	public void pesquisar() {
		this.getUsuarios();
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNomeusuario() {
		return nomeusuario;
	}

	public void setNomeusuario(String nomeusuario) {
		this.nomeusuario = nomeusuario;
	}

	public List<Usuario> getUsuarios() {
		this.usuarios = usuarioRN.listarTodos(getNomeusuario());
		return usuarios;
	}

}

morpheu/src/main/java/com/lmsystem/controller/cadastros/estoque/DepositoBean.java
package com.lmsystem.controller.cadastros.estoque;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Deposito;
import com.lmsystem.services.cadastros.estoque.DepositoRN;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class DepositoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Deposito deposito;

	private List<Deposito> depositos;

	private String nomedeposito;

	@Inject
	protected DepositoRN depositoRN;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomedeposito("");
		pesquisar();
	}

	public void novo() {
		this.setDeposito(new Deposito());
	}

	public void salvar() {
		try {
			depositoRN.salvar(this.deposito);
			this.deposito = new Deposito();
			this.pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.deposito = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			depositoRN.remover(this.deposito);
			this.pesquisar();
			facesUtils.exibeSucesso("Registro removido com sucesso!", null);
			this.deposito = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public String limpar() {
		return "deposito?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/estoque/deposito", opcoes, null);
	}

	public void pesquisar() {
		this.getDepositos();
	}

	public List<Deposito> listarDepositos(String query) {
		return depositoRN.listarTodos(query);
	}

	public Deposito getDeposito() {
		return deposito;
	}

	public void setDeposito(Deposito deposito) {
		this.deposito = deposito;
	}

	public List<Deposito> getDepositos() {
		this.depositos = depositoRN.listarTodos(getNomedeposito());
		return depositos;
	}

	public String getNomedeposito() {
		return nomedeposito;
	}

	public void setNomedeposito(String nomedeposito) {
		this.nomedeposito = nomedeposito;
	}

}

morpheu/src/main/webapp/paginas/cadastros/usuario.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<ui:define name="titulo">LMSystem - Cadastro de usuários</ui:define>
	<ui:define name="corpo">
		<f:metadata>
			<f:viewAction action="#{usuarioBean.iniciar}" />
		</f:metadata>
		<div class="ui-fluid">
			<p:panel header="Cadastro de usuário" styleClass="panel-formulario">
				<h:form id="frm-usuario">
					<p:focus for="usuario-nome"/>
					<p:panelGrid columns="2" layout="grid" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-1, ui-grid-col-7">
						<p:panelGrid>
							<h:outputLabel value="Código" for="codigo" />
							<p:inputText id="codigo" disabled="#{empty usuarioBean.usuario}" styleClass="somente-leitura" readonly="true" value="#{usuarioBean.usuario.pkusuario}" />
						</p:panelGrid>
						<p:panelGrid>
							<h:outputLabel value="Nome do usuário" for="usuario-nome" />
							<p:inputText id="usuario-nome"  onkeyup="maiusculo(this)" disabled="#{empty usuarioBean.usuario}" required="true" value="#{usuarioBean.usuario.nome}" />
						</p:panelGrid>
					</p:panelGrid>
					<p:panelGrid columns="4" layout="grid" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-2, ui-grid-col-2, ui-grid-col-2, ui-grid-col-2">
						<p:panelGrid>
							<h:outputLabel value="Login" for="usuario-login" />
							<p:inputText id="usuario-login" required="true" disabled="#{empty usuarioBean.usuario}" value="#{usuarioBean.usuario.login}"/>
						</p:panelGrid>
						<p:panelGrid>
							<h:outputLabel value="Senha" for="usuario-senha" />
							<p:password id="usuario-senha" disabled="#{empty usuarioBean.usuario}" redisplay="true" match="usuario-senha-confirmacao" feedback="true" inline="true" weakLabel="Fraca" goodLabel="Razoável" strongLabel="Excelente" promptLabel="Digite uma senha." required="true" value="#{usuarioBean.usuario.senha}" />
						</p:panelGrid>
						<p:panelGrid>
							<h:outputLabel value="Confirmar senha" for="usuario-senha-confirmacao" />
							<p:password id="usuario-senha-confirmacao" disabled="#{empty usuarioBean.usuario}" redisplay="true" feedback="true" inline="true" weakLabel="Fraca" goodLabel="Razoável" strongLabel="Excelente" promptLabel="Digite uma senha." required="true" value="#{usuarioBean.usuario.senha}"/>
						</p:panelGrid>
						<p:panelGrid>
							<h:outputLabel value="Tipo de Usuário" for="tipo-usuario" />
							<p:selectOneMenu id="tipo-usuario" value="#{usuarioBean.usuario.tipo}" rendered="#{not empty usuarioBean.usuario}" disabled="#{empty usuarioBean.usuario}">
								<f:selectItem itemLabel="Selecione"/>
								<f:selectItems value="#{usuarioBean.permissoes}" var="permissao"
								itemLabel="#{permissao.descricao}" itemValue="#{permissao}" />
							</p:selectOneMenu>
						</p:panelGrid>
					</p:panelGrid>
					<p:panelGrid columns="3" layout="grid" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-1, ui-grid-col-1, ui-grid-col-1">
						<p:commandButton value="Novo" action="#{usuarioBean.novo}" rendered="#{empty usuarioBean.usuario}" update="frm-usuario" resetValues="true" immediate="true" />
						<p:commandButton value="Salvar" action="#{usuarioBean.salvar}" icon="fa fa-save" rendered="#{not empty usuarioBean.usuario}" update="frm-usuario frm-localizar" />
						<p:commandButton value="Excluir" action="#{usuarioBean.remover}" 
							process="@this" icon="fa fa-remove" update="frm-usuario frm-localizar"
							disabled="#{empty usuarioBean.usuario.pkusuario}" >
							<p:confirm icon="ui-icon-alert" message="Tem certeza que deseja excluir o usuário?" />
						</p:commandButton>
						<p:commandButton value="Cancelar" action="#{usuarioBean.limpar}" icon="fa fa-refresh" disabled="#{empty usuarioBean.usuario}" immediate="true" />
					</p:panelGrid>
				</h:form>
				<p:separator/>
				<h:form id="frm-localizar">
					<p:panelGrid columns="3" layout="grid" id="pnl-pesquisa" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-5, ui-grid-col-1, ui-grid-col-6">
						<p:inputText id="nome-usuario" title="Pesquisa pelo nome do Usuário." onkeyup="maiusculo(this)" value="#{usuarioBean.nomeusuario}" placeholder="Descrição do Nome do Usuário" />
						<p:commandButton value="Pesquisar" action="#{usuarioBean.pesquisar}" icon="fa fa-search" update="frm-localizar" />
						<p:panelGrid columns="2" layout="grid" styleClass="panelgrid-noborder" style="float: right;">
							<p:commandLink title="Exportar para XLS" ajax="false" immediate="true" disabled="#{empty usuarioBean.usuarios}">
								<h:graphicImage library="img/png" name="xls.png" width="15" />
								<p:dataExporter type="xls" target="lista-de-usuarios" fileName="Relação de usuários"/>
							</p:commandLink>
							<p:commandLink title="Exporat para pdf" ajax="false" immediate="true" disabled="#{empty usuarioBean.usuarios}">
								<h:graphicImage library="img/png" name="pdf.png" width="15" />
			   					<p:dataExporter type="pdf" target="lista-de-usuarios" fileName="Relação de usuários" />
							</p:commandLink>
						</p:panelGrid>
					</p:panelGrid>
			  		<p:dataTable 
						value="#{usuarioBean.usuarios}" 
						id="lista-de-usuarios" 
						var="u"
						rows="10"
						emptyMessage="Nenhum registro satisfaz à pesquisa." 
			 			paginator="true" reflow="true"
			 			paginatorAlwaysVisible="false" 
			 			paginatorPosition="bottom"
			 			selection="#{usuarioBean.usuario}"
			 			selectionMode="single"
			 			rowKey="#{u.pkusuario}">		
			 				<p:ajax event="rowSelect" update="frm-usuario" />
			 				<p:ajax event="rowUnselect" update="frm-usuario" />
							<p:column headerText="Código" styleClass="coluna-codigo">
								<p:outputLabel value="#{u.pkusuario}"/>
							</p:column>
							<p:column headerText="Nome do usuário">
								<p:outputLabel value="#{u.nome}"/>
							</p:column>
							<p:column headerText="Login">
								<p:outputLabel value="#{u.login}"/>
							</p:column>
							<p:column headerText="Permissão" styleClass="coluna-cnpj">
								<p:outputLabel value="#{u.tipo.descricao}"/>
							</p:column>
					</p:dataTable>	
				</h:form>
			</p:panel>
		</div>
	</ui:define>
</ui:composition>