morpheu/src/main/java/com/lmsystem/controller/cadastros/PessoaFisicaBean.java
package com.lmsystem.controller.cadastros;

import java.io.IOException;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Bairro;
import com.lmsystem.modelo.Contato;
import com.lmsystem.modelo.Endereco;
import com.lmsystem.modelo.Etnia;
import com.lmsystem.modelo.Municipio;
import com.lmsystem.modelo.Nacionalidade;
import com.lmsystem.modelo.PessoaFisica;
import com.lmsystem.modelo.RacaCor;
import com.lmsystem.modelo.Sexo;
import com.lmsystem.modelo.TipoLogradouro;
import com.lmsystem.repository.BairroRepository;
import com.lmsystem.repository.MunicipioRepository;
import com.lmsystem.services.cadastros.PessoaFisicaRN;
import com.lmsystem.util.BuscaCEP;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class PessoaFisicaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private PessoaFisica pessoaFisica;

	private String nomePessoa;

	private List<PessoaFisica> pessoasFisica;

	@Inject
	protected PessoaFisicaRN pessoaRN;

	@Inject
	protected BairroRepository bairroRepository;

	@Inject
	protected MunicipioRepository municipioRepository;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomePessoa("");
		pesquisar();
	}

	public void novo() {
		this.pessoaFisica = new PessoaFisica();
		this.getPessoaFisica().setContato(new Contato());
		this.getPessoaFisica().setEndereco(new Endereco());
	}

	public void salvar() {
		try {
			pessoaRN.salvar(getPessoaFisica());
			pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.pessoaFisica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			pessoaRN.remover(this.getPessoaFisica());
			this.pesquisar();
			facesUtils.exibeSucesso("registro removido com sucesso!", null);
			this.pessoaFisica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
		}
	}

	public String limpar() {
		return "pessoafisica?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		opcoes.put("resizable", false);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/pessoafisica", opcoes, null);
	}

	public void pesquisar() {
		this.getPessoasFisicas();
	}

	public void buscarCEP() {
		BuscaCEP cep = new BuscaCEP();
		try {
			if (!this.getPessoaFisica().getEndereco().getCep().trim().equals("")
					|| this.getPessoaFisica().getEndereco().getCep() != null) {
				String tmp = cep.getCidade(this.getPessoaFisica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaFisica().getEndereco()
							.setMunicipio(municipioRepository.buscarPorDescricao("municipio", tmp).get(0));
					tmp = null;
				}
				tmp = cep.getEndereco(this.getPessoaFisica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaFisica().getEndereco().setEndereco(tmp);
					tmp = null;
				}
				tmp = cep.getBairro(this.getPessoaFisica().getEndereco().getCep());
				if (tmp != null) {
					System.out.println(tmp);
					this.getPessoaFisica().getEndereco()
							.setBairro(bairroRepository.buscarPorDescricao("bairro", tmp).get(0));
					tmp = null;
				}
			}
		} catch (IOException e) {
			System.out.println("Endereço não encontrado!");
			e.printStackTrace();
		}
	}

	private List<PessoaFisica> getPessoasFisicas() {
		pessoasFisica = pessoaRN.listarTodos(getNomePessoa());
		return pessoasFisica;
	}

	public PessoaFisica getPessoaFisica() {
		return pessoaFisica;
	}

	public void setPessoaFisica(PessoaFisica pessoaFisica) {
		this.pessoaFisica = pessoaFisica;
	}

	public String getNomePessoa() {
		return nomePessoa;
	}

	public void setNomePessoa(String nomePessoa) {
		this.nomePessoa = nomePessoa;
	}

	public List<Sexo> listarSexos(String query) {
		return pessoaRN.listarSexos(query);
	}

	public List<RacaCor> listarRacasCor(String query) {
		return pessoaRN.listarRacasCor(query);
	}

	public List<Etnia> listarEtnias(String query) {
		return pessoaRN.listarEtnias(query);
	}

	public List<Municipio> listarMunicipios(String query) {
		return pessoaRN.listarMunicipios(query);
	}

	public List<Nacionalidade> listarNacionalidades(String query) {
		return pessoaRN.ListarNacionalidades(query);
	}

	public List<TipoLogradouro> listarTiposLogradouro(String query) {
		return pessoaRN.listarTipoLogradouros(query);
	}

	public List<Bairro> listarBairros(String query) {
		return pessoaRN.listarBairros(query);
	}

	public List<PessoaFisica> getPessoasFisica() {
		this.pessoasFisica = pessoaRN.listarTodos(getNomePessoa());
		return pessoasFisica;
	}
}

morpheu/src/main/java/com/lmsystem/controller/cadastros/PessoaJuridicaBean.java
package com.lmsystem.controller.cadastros;

import java.io.IOException;
import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Bairro;
import com.lmsystem.modelo.Contato;
import com.lmsystem.modelo.Endereco;
import com.lmsystem.modelo.Municipio;
import com.lmsystem.modelo.PessoaJuridica;
import com.lmsystem.modelo.TipoLogradouro;
import com.lmsystem.repository.BairroRepository;
import com.lmsystem.repository.MunicipioRepository;
import com.lmsystem.services.cadastros.PessoaJuridicaRN;
import com.lmsystem.util.BuscaCEP;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class PessoaJuridicaBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private PessoaJuridica pessoaJuridica;

	private String nomefantasia;

	private List<PessoaJuridica> pessoasJuridica;

	@Inject
	protected PessoaJuridicaRN pessoaRN;

	@Inject
	protected BairroRepository bairroRepository;

	@Inject
	protected MunicipioRepository municipioRepository;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomefantasia("");
		pesquisar();
	}

	public void novo() {
		this.pessoaJuridica = new PessoaJuridica();
		this.getPessoaJuridica().setContato(new Contato());
		this.getPessoaJuridica().setEndereco(new Endereco());
	}

	public void salvar() {
		try {
			pessoaRN.salvar(getPessoaJuridica());
			pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.pessoaJuridica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			pessoaRN.remover(this.getPessoaJuridica());
			this.pesquisar();
			facesUtils.exibeSucesso("registro removido com sucesso!", null);
			this.pessoaJuridica = null;
			iniciar();
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
		}
	}

	public String limpar() {
		return "pessoajuridica?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		opcoes.put("resizable", false);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/pessoajuridica", opcoes, null);
	}

	public void pesquisar() {
		this.getPessoasFisicas();
	}

	public void buscarCEP() {
		BuscaCEP cep = new BuscaCEP();
		try {
			if (!this.getPessoaJuridica().getEndereco().getCep().trim().equals("")
					|| this.getPessoaJuridica().getEndereco().getCep() != null) {
				String tmp = cep.getCidade(this.getPessoaJuridica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaJuridica().getEndereco()
							.setMunicipio(municipioRepository.buscarPorDescricao("municipio", tmp).get(0));
					tmp = null;
				}
				tmp = cep.getEndereco(this.getPessoaJuridica().getEndereco().getCep());
				if (tmp != null) {
					this.getPessoaJuridica().getEndereco().setEndereco(tmp);
					tmp = null;
				}
				tmp = cep.getBairro(this.getPessoaJuridica().getEndereco().getCep());
				if (tmp != null) {
					System.out.println(tmp);
					this.getPessoaJuridica().getEndereco()
							.setBairro(bairroRepository.buscarPorDescricao("bairro", tmp).get(0));
					tmp = null;
				}
			}
		} catch (IOException e) {
			System.out.println("Endereço não encontrado!");
			e.printStackTrace();
		}
	}

	private List<PessoaJuridica> getPessoasFisicas() {
		pessoasJuridica = pessoaRN.listarTodos(getNomefantasia());
		return pessoasJuridica;
	}

	public PessoaJuridica getPessoaJuridica() {
		return pessoaJuridica;
	}

	public void setPessoaJuridica(PessoaJuridica pessoaJuridica) {
		this.pessoaJuridica = pessoaJuridica;
	}

	public String getNomefantasia() {
		return nomefantasia;
	}

	public void setNomefantasia(String nomefantasia) {
		this.nomefantasia = nomefantasia;
	}

	public List<Municipio> listarMunicipios(String query) {
		return pessoaRN.listarMunicipios(query);
	}

	public List<TipoLogradouro> listarTiposLogradouro(String query) {
		return pessoaRN.listarTipoLogradouros(query);
	}

	public List<Bairro> listarBairros(String query) {
		return pessoaRN.listarBairros(query);
	}

	public List<PessoaJuridica> getPessoasJuridica() {
		this.pessoasJuridica = pessoaRN.listarTodos(getNomefantasia());
		return pessoasJuridica;
	}
}

morpheu/src/main/java/com/lmsystem/controller/cadastros/SetorBean.java
package com.lmsystem.controller.cadastros;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Setor;
import com.lmsystem.services.cadastros.SetorRN;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class SetorBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Setor setor;

	private List<Setor> setores;

	private String nomesetor;

	@Inject
	protected SetorRN setorRN;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomesetor("");
		pesquisar();
	}

	public void novo() {
		this.setor = new Setor();
	}

	public void salvar() {
		try {
			setorRN.salvar(this.setor);
			this.setor = new Setor();
			this.pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.setor = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			setorRN.remover(this.setor);
			this.pesquisar();
			facesUtils.exibeSucesso("Registro removido com sucesso!", null);
			this.setor = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public String limpar() {
		return "setor?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/setor", opcoes, null);
	}

	public void pesquisar() {
		this.getSetores();
	}

	public List<Setor> listarSetores(String query) {
		return setorRN.listarTodos(query);
	}

	public Setor getSetor() {
		return setor;
	}

	public void setSetor(Setor setor) {
		this.setor = setor;
	}

	public List<Setor> getSetores() {
		this.setores = setorRN.listarTodos(getNomesetor());
		return setores;
	}

	public String getNomesetor() {
		return nomesetor;
	}

	public void setNomesetor(String nomesetor) {
		this.nomesetor = nomesetor;
	}

}

morpheu/src/main/java/com/lmsystem/controller/cadastros/UsuarioBean.java
package com.lmsystem.controller.cadastros;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.Permissoes;
import com.lmsystem.modelo.Usuario;
import com.lmsystem.services.cadastros.UsuarioRN;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class UsuarioBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private Usuario usuario;

	private String nomeusuario;

	private List<Usuario> usuarios;

	@Inject
	protected UsuarioRN usuarioRN;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomeusuario("");
		pesquisar();
	}

	public void novo() {
		this.usuario = new Usuario();
	}

	public void salvar() {
		try {
			usuarioRN.salvar(this.usuario);
			this.usuario = new Usuario();
			this.pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.usuario = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			usuarioRN.remover(this.usuario);
			this.pesquisar();
			facesUtils.exibeSucesso("Registro removido com sucesso!", null);
			this.usuario = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public String limpar() {
		return "usuario?faces-redirect=true";
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/usuario", opcoes, null);
	}
	
	public Permissoes[] getPermissoes() {
		return Permissoes.values();
	}

	public void pesquisar() {
		this.getUsuarios();
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getNomeusuario() {
		return nomeusuario;
	}

	public void setNomeusuario(String nomeusuario) {
		this.nomeusuario = nomeusuario;
	}

	public List<Usuario> getUsuarios() {
		this.usuarios = usuarioRN.listarTodos(getNomeusuario());
		return usuarios;
	}

}

morpheu/src/main/java/com/lmsystem/controller/cadastros/estoque/SubGrupoProdutoBean.java
package com.lmsystem.controller.cadastros.estoque;

import java.io.Serializable;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import com.lmsystem.modelo.GrupoProduto;
import com.lmsystem.modelo.SubGrupoProduto;
import com.lmsystem.services.cadastros.estoque.GrupoProdutoRN;
import com.lmsystem.services.cadastros.estoque.SubGrupoProdutoRN;
import com.lmsystem.util.FacesUtils;

@Named
@ViewScoped
public class SubGrupoProdutoBean implements Serializable {

	private static final long serialVersionUID = 1L;

	private SubGrupoProduto subgrupoProduto;

	private List<SubGrupoProduto> subgrupoProdutos;

	private String nomesubgrupo;

	@Inject
	protected SubGrupoProdutoRN subGrupoProdutoRN;

	@Inject
	protected GrupoProdutoRN grupoProdutoRN;

	@Inject
	protected FacesUtils facesUtils;

	public void iniciar() {
		this.setNomesubgrupo("");
		pesquisar();
	}

	public void novo() {
		this.subgrupoProduto = new SubGrupoProduto();
	}

	public void salvar() {
		try {
			subGrupoProdutoRN.salvar(this.subgrupoProduto);
			this.subgrupoProduto = new SubGrupoProduto();
			this.pesquisar();
			facesUtils.exibeSucesso("Registro cadastrado com sucesso!", null);
			this.subgrupoProduto = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível inserir o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void remover() {
		try {
			subGrupoProdutoRN.remover(this.subgrupoProduto);
			this.pesquisar();
			facesUtils.exibeSucesso("Registro removido com sucesso!", null);
			this.subgrupoProduto = null;
		} catch (Exception e) {
			facesUtils.exibeErro("não foi possível remover o registro!", null);
			System.out.println(e.getMessage());
			System.out.println(e.getCause());
		}
	}

	public void openWindow() {
		Map<String, Object> opcoes = new HashMap<>();
		opcoes.put("responsive", true);
		RequestContext.getCurrentInstance().openDialog("/paginas/cadastros/estoque/subgrupo-produto", opcoes, null);
	}

	public String limpar() {
		return "subgrupo-produto?faces-redirect=true";
	}

	public void pesquisar() {
		this.getSubGrupoProdutos();
	}

	public SubGrupoProduto getSubgrupoProduto() {
		return subgrupoProduto;
	}

	public void setSubgrupoProduto(SubGrupoProduto subgrupoProduto) {
		this.subgrupoProduto = subgrupoProduto;
	}

	public List<SubGrupoProduto> getSubGrupoProdutos() {
		this.subgrupoProdutos = subGrupoProdutoRN.listarTodos(getNomesubgrupo());
		return subgrupoProdutos;
	}

	public List<SubGrupoProduto> listarSubGrupoProdutos() {
		return subGrupoProdutoRN.listarTodos(getNomesubgrupo());
	}

	public List<GrupoProduto> listarGrupoProdutos(String query) {
		return grupoProdutoRN.listarTodos(query);
	}

	public String getNomesubgrupo() {
		return nomesubgrupo;
	}

	public void setNomesubgrupo(String nomesubgrupo) {
		this.nomesubgrupo = nomesubgrupo;
	}

}

morpheu/src/main/webapp/paginas/cadastros/estoque/estoque.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<ui:define name="corpo">
		<h:form>
 			<p:tabView orientation="top" effect="slide" style="font-size: 12px;" dynamic="true">
				<p:tab title="Produto" closable="true">
					<ui:include src="/paginas/cadastros/estoque/produto.xhtml" />
				</p:tab>
				<p:tab title="Subgrupo de produtos" closable="true">
					<ui:include src="/paginas/cadastros/estoque/subgrupo.xhtml"/>
				</p:tab>
				<p:tab title="Grupo de produtos" closable="true">
					<ui:include src="/paginas/cadastros/estoque/grupo.xhtml" />
				</p:tab>
				<p:tab title="Unidade" closable="true">
					<ui:include src="/paginas/cadastros/estoque/unidade.xhtml" />
				</p:tab>
				<p:tab title="Depósito" closable="true">
					<ui:include src="/paginas/cadastros/estoque/deposito.xhtml" />
				</p:tab>
			</p:tabView>
		</h:form>
	</ui:define>
</ui:composition>

morpheu/src/main/webapp/paginas/cadastros/estoque/subgrupo-produto.xhtml
<!DOCTYPE html>
<ui:composition template="/WEB-INF/templates/layout.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<ui:define name="titulo">LMSystem - Cadastro de subgrupos</ui:define>
	<ui:define name="corpo">
		<f:metadata>
			<f:viewAction action="#{subGrupoProdutoBean.iniciar}"/>
		</f:metadata>
		<div class="ui-fluid">
			<p:panel header="Cadastro de SubGrupo de Produtos" styleClass="panel-formulario">
				<h:form id="frm-subgrupo">
					<p:focus for="subgrupo"/>
					<p:panelGrid columns="2" layout="grid" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-1, ui-grid-col-5">
						<p:panelGrid>
							<h:outputLabel value="Código" for="codigo" />
							<p:inputText id="codigo" disabled="#{empty subGrupoProdutoBean.subgrupoProduto}" styleClass="somente-leitura" readonly="true" value="#{subGrupoProdutoBean.subgrupoProduto.pksubgrupo}" />
						</p:panelGrid>
						<p:panelGrid>
							<h:outputLabel value="Descrição do subgrupo" for="subgrupo" />
							<p:inputText id="subgrupo" required="true" onkeyup="maiusculo(this)" disabled="#{empty subGrupoProdutoBean.subgrupoProduto}" value="#{subGrupoProdutoBean.subgrupoProduto.subgrupo}" />
						</p:panelGrid>
					</p:panelGrid>
					<p:panelGrid columns="1" layout="grid" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-6">
						<p:outputLabel value="Grupo de Produtos" for="subgrupo-grupo" />
						<p:autoComplete id="subgrupo-grupo"
								value="#{subGrupoProdutoBean.subgrupoProduto.grupoProduto}"
								title="Grupo de produtos"  
								disabled="#{empty subGrupoProdutoBean.subgrupoProduto}"
								onkeyup="maiusculo(this)"
								var="grupo"
								itemValue="#{grupo}"
								itemLabel="#{grupo.grupoproduto}" 
								completeMethod="#{subGrupoProdutoBean.listarGrupoProdutos}"
								minQueryLength="1"
								maxResults="100"
								queryDelay="1000"
								effect="blind"
								dropdownMode="current"
								forceSelection="true"
								scrollHeight="150"/>
					</p:panelGrid>
					<p:panelGrid columns="3" layout="grid" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-1, ui-grid-col-1, ui-grid-col-1">
						<p:commandButton value="Novo" action="#{subGrupoProdutoBean.novo}" rendered="#{empty subGrupoProdutoBean.subgrupoProduto}" update="frm-subgrupo" />
						<p:commandButton value="Salvar" action="#{subGrupoProdutoBean.salvar}" icon="fa fa-save" rendered="#{not empty subGrupoProdutoBean.subgrupoProduto}" update="frm-subgrupo frm-localizar" />
						<p:commandButton value="Excluir" onsuccess="PF('confirmacao').show()" icon="fa fa-remove" disabled="#{empty subGrupoProdutoBean.subgrupoProduto.pksubgrupo}" />
						<p:commandButton value="Cancelar" action="#{subGrupoProdutoBean.limpar}" icon="fa fa-refresh" disabled="#{empty subGrupoProdutoBean.subgrupoProduto}" immediate="true" />
					</p:panelGrid>
				</h:form>
				<p:separator/>
				<h:form id="frm-localizar">
					<p:panelGrid columns="2" layout="grid" id="pnl-pesquisa" styleClass="panelgrid-noborder" columnClasses="ui-grid-col-4, ui-grid-col-1">
						<p:inputText id="nome-subgrupo" title="Pesquisa pelo nome do subgrupo de produtos." onkeyup="maiusculo(this)" value="#{subGrupoProdutoBean.nomesubgrupo}" placeholder="Descrição do SubGrupo de Produtos" />
						<p:commandButton value="Pesquisar" action="#{subGrupoProdutoBean.pesquisar}" icon="fa fa-search" update="frm-localizar" />
					</p:panelGrid>
					<p:dataTable 
						value="#{subGrupoProdutoBean.subGrupoProdutos}" 
						id="lista-de-subgrupos" 
						var="subgrupo"
						rows="10"
						emptyMessage="Nenhum registro satisfaz à pesquisa." 
			 			paginator="true" reflow="true"
			 			paginatorAlwaysVisible="false" 
			 			paginatorPosition="bottom"
			 			selection="#{subGrupoProdutoBean.subgrupoProduto}"
			 			selectionMode="single"
			 			rowKey="#{subgrupo.pksubgrupo}">
			 				<p:ajax event="rowDblselect" update="frm-subgrupo" />		 						 	
							<p:column headerText="Código" styleClass="coluna-codigo">
								<p:outputLabel value="#{subgrupo.pksubgrupo}"/>
							</p:column>
							<p:column headerText="SubGrupo">
								<p:outputLabel value="#{subgrupo.subgrupo}"/>
							</p:column>
							<p:column headerText="Grupo de produtos">
								<p:outputLabel value="#{subgrupo.grupoProduto.grupoproduto}"/>
							</p:column>
					</p:dataTable>					
				</h:form>
				<p:confirmDialog widgetVar="confirmacao" closable="false" showEffect="fade" hideEffect="fade" severity="alert" message="Deseja excluir o registro?">
					<h:form>
						<p:panelGrid columns="2" layout="grid" columnClasses="ui-grid-col-6,ui-grid-col-6" styleClass="panelgrid-noborder">
							<p:panelGrid>
								<p:commandButton value="SIM" onclick="confirmacao.hide()" action="#{subGrupoProdutoBean.remover}" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" update="frm-subgrupo frm-localizar" resetValues="true" />
							</p:panelGrid>
							<p:panelGrid>
								<p:commandButton value="NÃO" onclick="confirmacao.hide()" styleClass="ui-confirmdialog-no" icon="ui-icon-close" update="frm-subgrupo frm-localizar" />
							</p:panelGrid>
						</p:panelGrid>
					</h:form>
				</p:confirmDialog>
			</p:panel>
		</div>
	</ui:define>
</ui:composition>